"""Storage for the family hub.

Two interchangeable backends behind one tiny interface:

- **SQLite** (default) — zero-setup local file, used when no
  ``HUB_DATABASE_URL`` is set. Good for self-hosting on a box with a disk.
- **Postgres** (e.g. Supabase) — used when ``HUB_DATABASE_URL`` is a
  ``postgres://`` / ``postgresql://`` URL. Required on serverless hosts like
  Vercel, which have no persistent disk. Use Supabase's *transaction pooler*
  connection string (port 6543) for serverless deployments.

Application code writes SQLite-style SQL (``?`` placeholders); the Postgres
wrapper translates placeholders and both backends return mapping-style rows.
Use :func:`insert_id` instead of ``cursor.lastrowid`` so inserts work on both.
"""

import os
import sqlite3
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

DEFAULT_DB_PATH = str(Path(__file__).resolve().parent.parent / "hub.db")

# Schema targets shared by both backends: TEXT dates/times (ISO strings),
# INTEGER booleans. {ID} expands to each backend's autoincrement PK.
_SCHEMA_TEMPLATE = """
CREATE TABLE IF NOT EXISTS settings(
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS parents(
  id {ID},
  name TEXT NOT NULL,
  email TEXT UNIQUE,
  color TEXT NOT NULL DEFAULT '#3a86ff',
  password_hash TEXT,
  invite_token TEXT
);

CREATE TABLE IF NOT EXISTS kids(
  id {ID},
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#2a9d8f'
);

CREATE TABLE IF NOT EXISTS custody_schedule(
  id INTEGER PRIMARY KEY CHECK (id = 1),
  pattern TEXT NOT NULL,
  anchor_date TEXT NOT NULL,
  cycle TEXT NOT NULL,
  handoff_time TEXT NOT NULL DEFAULT '18:00'
);

CREATE TABLE IF NOT EXISTS custody_overrides(
  date TEXT PRIMARY KEY,
  parent_id INTEGER NOT NULL REFERENCES parents(id),
  swap_id INTEGER,
  note TEXT
);

CREATE TABLE IF NOT EXISTS events(
  id {ID},
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  date TEXT NOT NULL,
  start_time TEXT,
  end_time TEXT,
  all_day INTEGER NOT NULL DEFAULT 0,
  location TEXT NOT NULL DEFAULT '',
  notes TEXT NOT NULL DEFAULT '',
  series_id TEXT,
  created_by INTEGER REFERENCES parents(id),
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_date ON events(date);

CREATE TABLE IF NOT EXISTS event_kids(
  event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  kid_id INTEGER NOT NULL REFERENCES kids(id) ON DELETE CASCADE,
  PRIMARY KEY (event_id, kid_id)
);

CREATE TABLE IF NOT EXISTS swaps(
  id {ID},
  created_by INTEGER NOT NULL REFERENCES parents(id),
  status TEXT NOT NULL DEFAULT 'pending',
  reason TEXT NOT NULL DEFAULT '',
  range1_start TEXT NOT NULL,
  range1_end TEXT NOT NULL,
  range1_parent INTEGER NOT NULL REFERENCES parents(id),
  range2_start TEXT,
  range2_end TEXT,
  range2_parent INTEGER REFERENCES parents(id),
  created_at TEXT NOT NULL,
  decided_at TEXT,
  decided_by INTEGER REFERENCES parents(id),
  thread_id INTEGER
);

CREATE TABLE IF NOT EXISTS threads(
  id {ID},
  subject TEXT NOT NULL,
  kid_id INTEGER REFERENCES kids(id) ON DELETE SET NULL,
  swap_id INTEGER,
  created_by INTEGER REFERENCES parents(id),
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages(
  id {ID},
  thread_id INTEGER NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
  author_id INTEGER NOT NULL REFERENCES parents(id),
  body TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS feeds(
  id {ID},
  token TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  kind TEXT NOT NULL,
  kid_id INTEGER REFERENCES kids(id) ON DELETE CASCADE
);
"""

SCHEMA = _SCHEMA_TEMPLATE.format(ID="INTEGER PRIMARY KEY AUTOINCREMENT")
PG_SCHEMA = _SCHEMA_TEMPLATE.format(
    ID="INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
)


def db_path() -> str:
    return os.environ.get("HUB_DB", DEFAULT_DB_PATH)


# Query params some platforms append (Prisma/pooler hints) that libpq/psycopg
# would reject as unknown connection options.
_NON_LIBPQ_PARAMS = {"pgbouncer", "connection_limit", "pool_timeout", "supa", "schema"}


def _sanitize_pg_url(url: str) -> str:
    parts = urlsplit(url)
    if not parts.query:
        return url
    kept = [(k, v) for k, v in parse_qsl(parts.query)
            if k.lower() not in _NON_LIBPQ_PARAMS]
    return urlunsplit(
        (parts.scheme, parts.netloc, parts.path, urlencode(kept), parts.fragment)
    )


def database_url() -> str:
    """Postgres URL if configured: HUB_DATABASE_URL, or POSTGRES_URL as set
    automatically by the Vercel <-> Supabase integration."""
    url = os.environ.get("HUB_DATABASE_URL") or os.environ.get("POSTGRES_URL") or ""
    if url.startswith(("postgres://", "postgresql://")):
        return _sanitize_pg_url(url)
    return url


class PgConnection:
    """Thin wrapper giving a psycopg connection the sqlite3-ish interface the
    app uses: ``conn.execute(sql_with_question_marks, params)``."""

    is_postgres = True

    def __init__(self, raw):
        self.raw = raw

    @staticmethod
    def _translate(sql: str) -> str:
        return sql.replace("?", "%s")

    def execute(self, sql: str, params=()):
        return self.raw.execute(self._translate(sql), params)

    def executescript(self, sql: str):
        return self.raw.execute(sql)

    def commit(self):
        self.raw.commit()

    def close(self):
        self.raw.close()


def _pg_connect(url: str) -> PgConnection:
    import psycopg
    from psycopg.rows import dict_row

    # prepare_threshold=None keeps psycopg compatible with transaction-mode
    # poolers (Supabase's pooler / pgbouncer), which serverless deploys use.
    raw = psycopg.connect(url, row_factory=dict_row, prepare_threshold=None)
    return PgConnection(raw)


_initialized_targets: set[str] = set()


def connect(path: str | None = None):
    """Open a connection; the schema is ensured once per process per target.

    An explicit ``path`` always means SQLite (used by tests); otherwise
    ``HUB_DATABASE_URL`` selects Postgres when set.
    """
    url = database_url()
    if url.startswith(("postgres://", "postgresql://")) and path is None:
        conn = _pg_connect(url)
        target = url
    else:
        target = path or db_path()
        conn = sqlite3.connect(target)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON")
    if target not in _initialized_targets:
        init_db(conn)
        _initialized_targets.add(target)
    return conn


def init_db(conn) -> None:
    if getattr(conn, "is_postgres", False):
        conn.executescript(PG_SCHEMA)
    else:
        conn.executescript(SCHEMA)
    conn.commit()


def insert_id(conn, sql: str, params=()) -> int:
    """Run an INSERT and return the new row's id on either backend."""
    if getattr(conn, "is_postgres", False):
        cur = conn.execute(sql + " RETURNING id", params)
        return cur.fetchone()["id"]
    return conn.execute(sql, params).lastrowid


def get_setting(conn, key: str, default: str | None = None) -> str | None:
    row = conn.execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def set_setting(conn, key: str, value: str) -> None:
    conn.execute(
        "INSERT INTO settings(key, value) VALUES(?, ?) "
        "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )
    conn.commit()
